"""initial schema

Revision ID: 3db6ea1fd09a
Revises: 
Create Date: 2026-05-21 21:11:22.287297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db6ea1fd09a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engineer_id', sa.String(length=36), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('selector_name', sa.String(length=64), nullable=False),
    sa.Column('selector_version', sa.String(length=32), nullable=False),
    sa.Column('reconciliation_layout', sa.Enum('INLINE_HUNK', 'NO_HUNK', name='reconciliationlayout'), nullable=False),
    sa.Column('current_phase', sa.Enum('SUBMITTED', 'HYPOTHESIS', 'REVEALED', 'RECONCILIATION', 'COMPLETE', name='sessionphase'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.Enum('SUBMITTED', 'HYPOTHESIS', 'REVEALED', 'RECONCILIATION', 'COMPLETE', name='sessionphase'), nullable=False),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'phase', name='uq_phase_event_per_session')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('structural_label', sa.Text(), nullable=False),
    sa.Column('hunk_ref', sa.Text(), nullable=False),
    sa.Column('selector_rationale', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_RECONCILIATION', 'IN_DIALOGUE', 'AWAITING_DISPOSITION', 'CLOSED', name='regionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ordinal', name='uq_region_ordinal_per_session')
    )
    op.create_table('closure_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('teach_back_statement', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', name='closureverdict'), nullable=False),
    sa.Column('missing_aspects', sa.Text(), nullable=True),
    sa.Column('judge_model_id', sa.String(length=64), nullable=False),
    sa.Column('judge_prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'attempt_number', name='uq_closure_attempt_number')
    )
    op.create_table('dialogue_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ENGINEER', 'MODEL', name='dialoguerole'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'turn_index', name='uq_dialogue_turn_index')
    )
    op.create_table('dispositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED_AS_IS', 'FLAGGED_FOR_REDESIGN', 'CLOSED_WITH_DISAGREEMENT', name='dispositionstatus'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('hypothesis_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'revision_number', name='uq_hypothesis_revision_number')
    )
    with op.batch_alter_table('hypothesis_revisions', schema=None) as batch_op:
        batch_op.create_index('uq_hypothesis_locked_per_region', ['region_id'], unique=True, sqlite_where=sa.text('is_locked = 1'))

    op.create_table('readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliations')
    op.drop_table('readings')
    with op.batch_alter_table('hypothesis_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_hypothesis_locked_per_region', sqlite_where=sa.text('is_locked = 1'))

    op.drop_table('hypothesis_revisions')
    op.drop_table('dispositions')
    op.drop_table('dialogue_turns')
    op.drop_table('closure_attempts')
    op.drop_table('regions')
    op.drop_table('phase_events')
    op.drop_table('sessions')
    op.drop_table('engineers')
    # ### end Alembic commands ###
