"""v1.5 schema deltas: engagement threshold, source provenance, new closure modes, override and deferral fields

Revision ID: b308b508a8f2
Revises: d802882dbd30
Create Date: 2026-05-29 17:46:39.397357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b308b508a8f2'
down_revision: Union[str, Sequence[str], None] = 'd802882dbd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_reason', sa.Enum('VALUE', 'TOIL', 'DIFFICULTY', name='overridereason'), nullable=True))
        batch_op.add_column(sa.Column('disagreement_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('acknowledgment_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deferred', sa.Boolean(), server_default='0', nullable=False))
        # Alembic autogenerate does not detect enum value additions on a
        # column whose enum name is unchanged. The closure_mode column
        # gains ACKNOWLEDGED and ENGINEER_OVERRODE; the CHECK constraint
        # must be widened by hand.
        batch_op.alter_column(
            'closure_mode',
            existing_type=sa.Enum('JUDGE_PASSED', 'ENGINEER_DISAGREED', name='closuremode'),
            type_=sa.Enum('JUDGE_PASSED', 'ENGINEER_DISAGREED', 'ACKNOWLEDGED', 'ENGINEER_OVERRODE', name='closuremode'),
            existing_nullable=True,
        )

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_commit', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_range', sa.String(length=128), nullable=True))
        # server_default uses the enum NAME (uppercase), not value. The
        # CHECK constraint generated by sa.Enum lists names; a lowercase
        # default would violate it on backfilled rows.
        batch_op.add_column(sa.Column('engagement_threshold', sa.Enum('LOAD_BEARING_ONLY', 'DEFAULT', 'THOROUGH', name='engagementthreshold'), server_default='DEFAULT', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('engagement_threshold')
        batch_op.drop_column('source_range')
        batch_op.drop_column('source_commit')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column(
            'closure_mode',
            existing_type=sa.Enum('JUDGE_PASSED', 'ENGINEER_DISAGREED', 'ACKNOWLEDGED', 'ENGINEER_OVERRODE', name='closuremode'),
            type_=sa.Enum('JUDGE_PASSED', 'ENGINEER_DISAGREED', name='closuremode'),
            existing_nullable=True,
        )
        batch_op.drop_column('is_deferred')
        batch_op.drop_column('acknowledgment_note')
        batch_op.drop_column('disagreement_reason')
        batch_op.drop_column('override_reason')
