"""schema warts: hunk metadata, closure mode, microsecond phase events

Revision ID: d802882dbd30
Revises: 3db6ea1fd09a
Create Date: 2026-05-22 20:49:05.432184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd802882dbd30'
down_revision: Union[str, Sequence[str], None] = '3db6ea1fd09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Enum('ACCEPTED_AS_IS', 'FLAGGED_FOR_REDESIGN', name='dispositionstatus'),
               existing_nullable=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hunk', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('closure_mode', sa.Enum('JUDGE_PASSED', 'ENGINEER_DISAGREED', name='closuremode'), nullable=True))
        batch_op.drop_column('hunk_ref')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hunk_ref', sa.TEXT(), nullable=False))
        batch_op.drop_column('closure_mode')
        batch_op.drop_column('hunk')

    with op.batch_alter_table('dispositions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACCEPTED_AS_IS', 'FLAGGED_FOR_REDESIGN', name='dispositionstatus'),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###
